const constants = {
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_LOADER_VISIBILITY: 'SET_LOADER_VISIBILITY',
    SET_SEARCH_ERROR: 'SET_SEARCH_ERROR'
}

export default constants;